name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  compile-pgo-optimized-portable:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            triple: x86_64-unknown-linux-musl
          - os: ubuntu-22.04-arm
            triple: aarch64-unknown-linux-musl
          - os: macos-15-intel
            triple: x86_64-apple-darwin
          - os: macos-26
            triple: aarch64-apple-darwin
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
          - os: windows-11-arm
            triple: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install latest Rust
        run: rustup toolchain install stable --profile minimal
      - name: Add Target
        run: rustup target add ${{ matrix.triple }}
      - name: Add llvm-preview for PGO
        run: rustup component add llvm-tools-preview
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Cargo PGO
        run: cargo install cargo-pgo
      - name: Install Cargo Packager
        run: cargo install cargo-packager --locked
      - name: Build instrumented Binary
        run: cargo pgo instrument build -- --profile optimized --target ${{ matrix.triple }}
      - name: Run instrumented Binary
        run: pwsh ./scripts/collect-pgo-profiles.ps1 ${{ matrix.triple }}
      - name: Build PGO optimized Binary
        run: cargo pgo optimize build -- --profile optimized --target ${{ matrix.triple }}
      - name: Archive Release
        run: pwsh ./scripts/archive-release.ps1 ${{ matrix.triple }}
      - name: Run Cargo Packager
        run: cargo packager --profile optimized --target ${{ matrix.triple }}
      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/staggered-file-backup*

  compile-portable:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: windows-11-arm
            triple: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install latest Rust
        run: rustup toolchain install stable --profile minimal
      - name: Add Target
        run: rustup target add ${{ matrix.triple }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Cargo Packager
        run: cargo install cargo-packager --locked
      - name: Build Binary
        run: cargo build --profile optimized --target ${{ matrix.triple }}
      - name: Archive Release
        run: pwsh ./scripts/archive-release.ps1 ${{ matrix.triple }}
      - name: Run Cargo Packager
        run: cargo packager --profile optimized --target ${{ matrix.triple }}
      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/staggered-file-backup*
